// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbNZ6szV2OACekmgro-uYIn6oy_cPIjzk',
    appId: '1:1000517418845:web:6169efde8bfc5bc67fb2b4',
    messagingSenderId: '1000517418845',
    projectId: 'chat-c68cd',
    authDomain: 'chat-c68cd.firebaseapp.com',
    storageBucket: 'chat-c68cd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUDV7MVh-SgcfIUsumwcqAui3Z9t3wzg0',
    appId: '1:1000517418845:android:c0131c506e5f526d7fb2b4',
    messagingSenderId: '1000517418845',
    projectId: 'chat-c68cd',
    storageBucket: 'chat-c68cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALtoR_edy4BggBtqzT6LLIzWh-vnIRWZs',
    appId: '1:1000517418845:ios:ffc6ea1916f26bc07fb2b4',
    messagingSenderId: '1000517418845',
    projectId: 'chat-c68cd',
    storageBucket: 'chat-c68cd.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALtoR_edy4BggBtqzT6LLIzWh-vnIRWZs',
    appId: '1:1000517418845:ios:ffc6ea1916f26bc07fb2b4',
    messagingSenderId: '1000517418845',
    projectId: 'chat-c68cd',
    storageBucket: 'chat-c68cd.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbNZ6szV2OACekmgro-uYIn6oy_cPIjzk',
    appId: '1:1000517418845:web:fdf525296d2b27d97fb2b4',
    messagingSenderId: '1000517418845',
    projectId: 'chat-c68cd',
    authDomain: 'chat-c68cd.firebaseapp.com',
    storageBucket: 'chat-c68cd.firebasestorage.app',
  );
}
